# Problem: https://www.hackerrank.com/challenges/harry-potter-and-wands/problem


SELECT W.ID, WP.AGE, W.COINS_NEEDED, W.POWER
FROM WANDS W
JOIN WANDS_PROPERTY WP ON W.CODE = WP.CODE
JOIN (
    SELECT MIN(COINS_NEEDED) as MIN_COINS, W2.POWER, WP2.AGE
    FROM WANDS W2
    JOIN WANDS_PROPERTY WP2
    ON W2.CODE = WP2.CODE
    WHERE WP2.IS_EVIL = 0
    GROUP BY W2.POWER, WP2.AGE
) AS CHEAP_WANDS ON
    W.POWER = CHEAP_WANDS.POWER
    AND WP.AGE = CHEAP_WANDS.AGE
    AND W.COINS_NEEDED = CHEAP_WANDS.MIN_COINS
ORDER BY W.POWER DESC, WP.AGE DESC
